### PR TITLE
Fix bignum issue #5

### PR DESCRIPTION
**Pull request by idstein**
To avoid an overflow on array access (bignum vs long) see issue #5

Here are the entry_data_type formats
https://github.com/android/platform_frameworks_base/blob/master/include/androidfw/ResourceTypes.h

### CODE REVIEW

**Comment by devunwired** [comment]
I'm unclear on exactly what the issue is, or how to reproduce it. Can you explain further what causes the problem and perhaps provide a sample APK to demonstrate the failure? I'm happy to accept this change if I can see the problem and verify this fixes it.

The propsed changes made in the switch statement don't seem to relate to the area of the code where the error was originally reported.

**Comment by idstein** [comment]
You can reproduce the issue by simply creating an app with two resources. A drawable that references a color. 
In that particular case the current code will see a drawable with a data value referencing some very large value (0x7fppxxxx). That is a table entry referencing for instance a color from a different resource table entry. By looking at the specific type of each chunk entry we can derive the original type (real string, reference, dynamic table from aar library, null, color, dimension, ... See linked header file for all valid types). 

The switch statement tried to make a link between a resource table chunk type instead of looking at the specific data of each resource table chunk entry. Assuming that all entries in a single resource table have the same data (e.g. string or drawable), references to other tables resulted in a sort of overflow. Because each table can only hold up to id 0xFFFF. But a misinterpret data value could be interpret as an invalid is up to 0xFFFFFFF which results in a bignum to long conversion error (at least on 32bit Ruby). 
Despite the conversion would result in an invalid string table reference id.

**Comment by idstein** [comment]
Unfortunately, I can not provide you with the exactAPK I used to produce that error (internal enterprise app). But we are running Windows with Ruby 1.9.3 (isn't that a 32bit only?) and DevKit-tdm-32bit.

**Comment by devunwired** [comment]
@idstein thus far, I am unable to reproduce the noted error—even with resources that point as references to others (I used a string and color with values referencing other similar resources). I would appreciate if you could provide a more discrete example that makes this reproducible. I don't need the entire APK, just some XML describing the resource reference(s) causing the exception. Then I can reconstruct my own test case.

You are likely correct about the cause, but it seems to only trigger in a specific case so I would like to make sure I can see the failure before assuming any changes fix the problem. I'd ask the original requestor, but the issue is many years old.

**Comment by devunwired** [comment]
Okay, I still can't reproduce this (even in a 32-bit environment), but after looking into it some more I can see where the issue would come from. Regardless, I like your approach of selecting based on data type rather than resource type. I had to make a few bug fixes today. If you update your branch to resolve the conflicts, I will merge it and cut another release after some cleanup.

**Comment by idstein** [comment]
[...]

Resource table:
Package Groups (1)
Package Group 0 id=0x7f packageCount=1 name=info.idstein.some.package
  Package 0 id=0x7f name=info.idstein.some.package
    type 0 configCount=1 entryCount=60
      [...]
      config (default):
        [...]
    type 1 configCount=8 entryCount=366
      [...]
      config anydpi-v21:
        [...]
      config (default):
        [...]
        resource 0x7f020153 info.idstein.some.package:drawable/some_color_reference: t=0x01 d=0x7f0d002a (s=0x0008 r=0x00)
        [...]
        resource 0x7f020156 info.idstein.some.package:drawable/color_rgb8_as_drawable: t=0x1d d=0xff99126d (s=0x0008 r=0x00)
		[...]
        resource 0x7f02015d info.idstein.some.package:drawable/color_argb8_as_drawable: t=0x1c d=0x77878c96 (s=0x0008 r=0x00)
        [...]
      config ldpi-v4:
        [...]
      config mdpi-v4:
        [...]
      config hdpi-v4:
        [...]
      config xhdpi-v4:
        [...]
      config xxhdpi-v4:
        [...]
      config xxxhdpi-v4:
        [...]
    type 2 configCount=6 entryCount=53
      [...]
      config (default):
        [...]
      config large-v4:
        [...]
      config xlarge-v4:
        [...]
      config v17:
        [...]
      config land:
        [...]
      config large-hdpi-v4:
        [...]
    type 3 configCount=1 entryCount=1
      [...]
      config (default):
        [...]
    type 4 configCount=1 entryCount=1
      [...]
      config (default):
        [...]
    type 5 configCount=1 entryCount=3
      [...]
      config (default):
        [...]
    type 6 configCount=7 entryCount=355
      [...]
      config (default):
        [...]
      config da:
        [...]
      config de:
        [...]
      config nl:
        [...]
      config pl:
        [...]
      config ro:
        [...]
      config fr:
        [...]
    type 7 configCount=2 entryCount=6
      [...]
      config (default):
        [...]
      config de:
        [...]
    type 8 configCount=2 entryCount=3
      [...]
      config (default):
        [...]
      config de:
        [...]
    type 9 configCount=7 entryCount=47
      [...]
      config (default):
        [...]
		resource 0x7f0a0009 info.idstein.some.package:dimen/real_dimension: t=0x05 d=0x00001001 (s=0x0008 r=0x00)
        resource 0x7f0a001e info.idstein.some.package:dimen/dimension_reference: t=0x01 d=0x7f0a0009 (s=0x0008 r=0x00)
        [...]
      config xlarge-v4:
        [...]
      config w600dp-v13:
        [...]
      config w800dp-v13:
        [...]
      config large-mdpi-v4:
        [...]
      config large-tvdpi-v4:
        [...]
      config large-hdpi-v4:
        [...]
    type 10 configCount=2 entryCount=89
      [...]
      config (default):
        [...]
      config v11:
        [...]
    type 11 configCount=1 entryCount=2
      [...]
      config (default):
        resource 0x7f0c0000 info.idstein.some.package:bool/boolean_true: t=0x12 d=0xffffffff (s=0x0008 r=0x00)
        resource 0x7f0c0001 info.idstein.some.package:bool/boolean_false: t=0x12 d=0x00000000 (s=0x0008 r=0x00)
    type 12 configCount=1 entryCount=174
      [...]
      config (default):
        [...]
        resource 0x7f0d002a info.idstein.some.package:color/color_argb8: t=0x1c d=0xff313131 (s=0x0008 r=0x00)
        [...]
        resource 0x7f0d0033 info.idstein.some.package:color/color_rgb8: t=0x1d d=0xfff8eb54 (s=0x0008 r=0x00)
        [...]
        resource 0x7f0d00ad info.idstein.some.package:color/color_another_reference: t=0x01 d=0x7f0d0033 (s=0x0008 r=0x00)
    type 13 configCount=1 entryCount=349
      [...]
      config (default):
        resource 0x7f0e0002 info.idstein.some.package:id/a_string: t=0x03 d=0x00000332 (s=0x0008 r=0x00)
        [...]
        resource 0x7f0e015c info.idstein.some.package:id/identifier_only: t=0x12 d=0x00000000 (s=0x0008 r=0x00)
    type 14 configCount=1 entryCount=1
      [...]
      config (default):
        resource 0x7f0f0000 info.idstein.some.package:integer/some_integer: t=0x10 d=0x00000000 (s=0x0008 r=0x00)
    type 15 configCount=1 entryCount=7
      [...]
      config (default):
        resource 0x7f100000 info.idstein.some.package:menu/some_string_stuff: t=0x03 d=0x00000007 (s=0x0008 r=0x00)
        [...]

Here's an example of using aapt l -a my.apk. As you can see the data may reference something completely different than a String for drawables, strings, colors.

I will reintegrate your commits to the branch starting now. The changes are trivial and I will leave out shortening the get_resource_string method as this is only to reduce unnecessary local variables.

**Comment by idstein** [comment]
I've created issue #14 to describe the reference following. I think as this can become sort of a loop issue, there must be a smarter algorithm during access time of the real value that needs to be resolved.

**Pull request merged**
